<?php

$MONNAIE = array(
"ALL" => "ALL (Lek d'Albanie)",
"AUD" => "AUD (Dollar Australien)",
"BGN" => "BGN (Lev de Bulgarie)",
"BIF" => "BIF (Franc du Burundi)",
"CAD" => "CAD (Dollar Canadien)",
"CDF" => "CDF (Franc congolais (RD))",
"CHF" => "CHF (Franc suisse)",
"CVE" => "CVE (Escudo-Cap-Verts)",
"DZD" => "DZD (Dinar Algerien)",
"EGP" => "EGP (Livre egyptienne)",
"EUR" => "EUR (Euro)",
"GEL" => "GEL (Lari géorgien)",
"GNF" => "GNF (Franc Guinéen)",
"HTG" => "HTG (Gourde de Haiti)",
"KHR" => "KHR (Riel du Cambodge)",
"KMF" => "KMF (Franc comorien)",
"LAK" => "LAK (Kip du laos)",
"LBP" => "LBP (Livre Libanaise)",
"MAD" => "MAD (Dirham marocain)",
"MDL" => "MDL (Leu Moldave)",
"MGA" => "MGA (Ariary de Madagascar)",
"MRO" => "MRO (Ouguiya de Mauritanie)",
"MUR" => "MUR (Roupie de Maurice)",
"RON" => "RON (Leu de Roumanie)",
"RWF" => "RWF (Franc du Rwanda)",
"SYP" => "SYP (Livre Syrienne)",
"THB" => "THB (Baht de Thaïlande)",
"TND" => "TND (Dinar tunisien)",
"TRY" => "TRY (Livre Turque)",
"USD" => "USD (Dollar des États-Unis)",
"VND" => "VND (Dong du Vietnam)",
"VUV" => "VUV (Vatu République du Vanuatu)",
"XAF" => "XAF (Franc CFA BEAC)",
"XOF" => "XOF (Franc CFA BCEAO)"
) ;


$DEVISE_MIGRATION = array(
	"ALL" => "ALL (Lek d'Albanie)",
"AMD" => "", // "Dram (Arménie)"
	"AUD" => "AUD (Dollar Australien)",
	"BGN" => "BGN (Lev de Bulgarie)",
	"BIF" => "BIF (Franc du Burundi)",
"BRL" => "",
	"CAD" => "CAD (Dollar Canadien)",
	"CDF" => "CDF (Franc congolais (RD))",
	"CHF" => "CHF (Franc suisse)",
"CNY" => "",
	"CVE" => "CVE (Escudo-Cap-Verts)",
	"DZD" => "DZD (Dinar Algerien)",
	"EGP" => "EGP (Livre egyptienne)",
	"EUR" => "EUR (Euro)",
	"GEL" => "GEL (Lari géorgien)",
	"GNF" => "GNF (Franc Guinéen)",
	"HTG" => "HTG (Gourde de Haiti)",
	"KHR" => "KHR (Riel du Cambodge)",
	"KMF" => "KMF (Franc comorien)",
	"LAK" => "LAK (Kip du laos)",
	"LBP" => "LBP (Livre Libanaise)",
	"MAD" => "MAD (Dirham marocain)",
	"MDL" => "MDL (Leu Moldave)",
	"MGA" => "MGA (Ariary de Madagascar)",
"MGF" => "",
"MKD" => "",
	"MRO" => "MRO (Ouguiya de Mauritanie)",
	"MUR" => "MUR (Roupie de Maurice)",
"MZN" => "",
"ROL" => "",
	"RON" => "RON (Leu de Roumanie)",
	"RWF" => "RWF (Franc du Rwanda)",
	"SYP" => "SYP (Livre Syrienne)",
	"THB" => "THB (Baht de Thaïlande)",
	"TND" => "TND (Dinar tunisien)",
	"TRY" => "TRY (Livre Turque)",
	"USD" => "USD (Dollar des États-Unis)",
	"VND" => "VND (Dong du Vietnam)",
	"VUV" => "VUV (Vatu République du Vanuatu)",
	"XAF" => "XAF (Franc CFA BEAC)",
	"XOF" => "XOF (Franc CFA BCEAO)",
"" => "",
) ;



?>
